### ISSUE TITLE
Create Login new KTS 3

### ISSUE THREAD

**Issue by Xsazor** [Budiyantoangga/KTS_Repository#8]
Creating a wonderful login page using AdminLTE Template (if any issue found, i will comment it) !

![login-page](https://github.com/user-attachments/assets/fbf97331-e29a-46d3-9ad1-cfa96dce634e)

**Comment by Budiyantoangga** [comment]
Great job!
Mas Lutfi, please create a list of modules in our project management tool and provide updates on the progress for each module.
This will help us prepare weekly reports for Pak Tedy and Pak Irlandie.

**Comment by gunartha** [comment]
Integrasi login form and db have done.

**Comment by Budiyantoangga** [comment]
Mantuuull Pak Man.
